services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ragai
    labels:
      - 'org.springframework.boot.service-connection=postgres'
    ports:
      - "5433:5432"